apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-coaching-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-coaching
  template:
    metadata:
      labels:
        app: service-coaching
    spec:
      containers:
        - name: service-coaching
          image: brucegroverlee/speeky-service-coaching
          resources:
            limits:
              memory: 512Mi
              cpu: '1'
            requests:
              memory: 128Mi
              cpu: '0.2'
          env:
            - name: DEBUG
              value: 'server:*'
            - name: NODE_ENV
              value: 'dev'
            - name: PORT
              value: '4000'
            - name: MONGODB_URL
              value: 'mongodb://service-coaching-mongo-srv:27017'
            - name: MONGODB_DBNAME
              value: 'speeky'
            - name: RABBITMQ_URL
              value: 'amqp://rabbit-srv/speeky'
            - name: RABBITMQ_CONNECTION_NAME
              value: 'coaching_service'
            - name: RABBITMQ_EXCHANGE
              value: 'event_bus'
            - name: RABBITMQ_EXCHANGE_TYPE
              value: 'topic'
            - name: RABBITMQ_QUEUE
              value: 'coaching_service_queue'
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: './gcp-service-account.json'
---
apiVersion: v1
kind: Service
metadata:
  name: service-coaching-srv
spec:
  type: NodePort
  selector:
    app: service-coaching
  ports:
    - name: service-coaching
      protocol: TCP
      port: 4000
      targetPort: 4000
